# Generated by Django 5.0 on 2023-12-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
